### ISSUE TITLE
When requesting all resource, its formatting the headers incorrectly for your API

### ISSUE THREAD

**Issue by tsteuwer-accesso** [cloudflare/cf-terraforming#123]
After having some issues with #122, I was finally able to get cf-terraforming running. When trying to fetch all resource, I get the following error:

```
troy.s$ 
troy.s$  go run /Users/troy.s/go/src/github.com/cloudflare/cf-terraforming/cmd/cf-terraforming --email $MYEMAIL --key $MYKEY --account $MYACCOUNTID all
   ERRO[0000] error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}" 
troy.s$ 
```

**Comment by dyipon** [comment]
same here

**Comment by squiddy** [comment]
Same issue here.

Looking at the code (https://github.com/cloudflare/cf-terraforming/blob/master/internal/app/cf-terraforming/cmd/root.go#L145), it seems that you either have to provide (`key` and `email`) or `token`. Not clear about the difference between key and token, but when I switched arguments it worked.

So maybe try `--token` instead of `--email / --key` combo.

**Comment by patryk** [comment]
I have added some more details in Readme on authentication.
