### ISSUE TITLE
Insufficient permissions to access zone

### ISSUE THREAD

**Issue by shuang703** [cloudflare/cf-terraforming#180]
Using the latest version of cf-terraforming as of today.  We have a mix of free, business and enterprise accounts.

Similar to the previously opened issue on this (https://github.com/cloudflare/cf-terraforming/issues/90), I'm able to import some resources but not all.  

Running ```cf-terraforming --email <accountemail> --account <account id> --key <global api key> access_application``` gives 
```
ERRO[0000] Insufficient permissions to access zone       ID=<zone id>
```

I've also tried this with ```cf-terraforming --email <accountemail> --token <api token``` (where the api token is a custom token that grants read access on all resources, including all accounts and all zones).  

Is there something I'm missing here?

**Comment by janekwonner** [comment]
I have the same issue

**Comment by kcantrel** [comment]
I also have this problem, as well as a problem getting access_policy. Oddly enough, get a slightly different error message:
```ERRO[0000] error from makeRequest: HTTP status 403: Authentication error ```

**Comment by patryk** [comment]
Hi, there are two separate issues here:
- due to a bug, the `--account` flag was not limiting the list of zones from different accounts you have access to, I'm fixing it
- the `Insufficient permissions to access zone` message most likely refers to Cloudflare Access not being activated on a specific account, it is actually described in error message from the API, which I'm about to display

Thanks for report.

**Comment by patryk** [comment]
Fixed.
