### ISSUE TITLE
cf-terraforming does not work on mac

### ISSUE THREAD

**Issue by DovilasK** [cloudflare/cf-terraforming#251]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.1.1

### Expected outcome

cf-terraforming generate --resource-type "cloudflare_record" --account $CLOUDFLARE_ACCOUNT_ID

Should export Cloudflare Records

### Actual outcome

FATA[0002] unexpected error: openpgp: signature made by unknown entity

### Steps to reproduce

cf-terraforming generate --resource-type "cloudflare_record" --account $CLOUDFLARE_ACCOUNT_ID
FATA[0002] unexpected error: openpgp: signature made by unknown entity

**Comment by jacobbednarz** [comment]
`cf-terraforming` doesn't use GPG anywhere so I'm assuming this is coming from Terraform and it is caused by the recent signing key exposure (and subsequent revocation) - https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512

To workaround, you'll need to upgrade the version of Terraform in use to the latest patch release to get the new key.

**Comment by thoomson** [comment]
Hello,

I've got the same issue. I've already the latest version of Terraform and cf-terraforming.

Do you have any idea of what can cause this issue ?

I've found nothing interesting in the hashicorp forum

Thanks

**Comment by DovilasK** [comment]
Yeah, im also with latest terraform version..

**Comment by ianmclaughlin98** [comment]
Also latest terraform version and fresh install and cannot run cf-terraforming. I don't think this issue should be closed.

**Comment by jacobbednarz** [comment]
#250 has been merged which should fix this. I'll confirm later today and cut a release if it does.

**Comment by ianmclaughlin98** [comment]
@jacobbednarz Could you please confirm this issue is fixed? I'm still running into this issue. Steps taken on mac:
`brew uninstall cf-terraforming`   
`brew tap cloudflare/cloudflare`
`brew install --cask cloudflare/cloudflare/cf-terraforming`
When I try and run a cf-terraforming command I get the popup saying it cannot be opened. Full error message:
`“cf-terraforming” cannot be opened because the developer cannot be verified.`
`macOS cannot verify that this app is free from malware. Homebrew Cask downloaded this file on April 28, 2021 from github.com.`

Is it possible I'm not clearing a cache properly?

**Comment by DovilasK** [comment]
> @jacobbednarz Could you please confirm this issue is fixed? I'm still running into this issue. Steps taken on mac:
> 
> `brew uninstall cf-terraforming`   
> 
> `brew tap cloudflare/cloudflare`
> 
> `brew install --cask cloudflare/cloudflare/cf-terraforming`
> 
> When I try and run a cf-terraforming command I get the popup saying it cannot be opened. Full error message:
> 
> `“cf-terraforming” cannot be opened because the developer cannot be verified.`
> 
> `macOS cannot verify that this app is free from malware. Homebrew Cask downloaded this file on April 28, 2021 from github.com.`
> 
> 
> 
> Is it possible I'm not clearing a cache properly?

Open Security and Privacy on mac and hit open or allow. That's it

**Comment by ianmclaughlin98** [comment]
> > @jacobbednarz Could you please confirm this issue is fixed? I'm still running into this issue. Steps taken on mac:
> > `brew uninstall cf-terraforming`
> > `brew tap cloudflare/cloudflare`
> > `brew install --cask cloudflare/cloudflare/cf-terraforming`
> > When I try and run a cf-terraforming command I get the popup saying it cannot be opened. Full error message:
> > `“cf-terraforming” cannot be opened because the developer cannot be verified.`
> > `macOS cannot verify that this app is free from malware. Homebrew Cask downloaded this file on April 28, 2021 from github.com.`
> > Is it possible I'm not clearing a cache properly?
> 
> Open Security and Privacy on mac and hit open or allow. That's it

Did this, still brings me back to the `FATA[0000] unexpected error: openpgp: signature made by unknown entity` issue

**Comment by jacobbednarz** [comment]
@ianmclaughlin98 please open a new issue following the issue template if you are still having issues and we can dig into it separately.
