### ISSUE TITLE
Error "FATA[0002] configuration is invalid" doesn't give troubleshooting information

### ISSUE THREAD

**Issue by chris-zenfolio** [cloudflare/cf-terraforming#314]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.4.0

### Expected outcome

When I get an error, I need information to be able to troubleshoot it.  What is error code 0002?  What specifically is wrong with the "configuration"?  Did I miss a parameter?  Did the API return a weird value because I queried for a feature not supported/enabled on my account?  Even when running --verbose, there is not enough information to troubleshoot this generic error.  I looked through the source code and see all the entries where log.Fatal(err) is called, but can never find the definitions for 'err' to trace my problem.

I expect specific-enough information to tell me why the error happened.

### Actual outcome

I wrote a shell script to iterate through the current supported generate resource-types (since, despite the Cloudflare Blog's statements otherwise, you cannot query for "all") in an effort to capture my environment so I could replicate it with Terraform (parked domains, same configs, easy-peasy...not).

Any time there was an error, every cf-terraforming generate output after it also generated the error.  I can also reproduce it manually.

Here is sample output (sanitized.  PM me for un-sanitized results).  Note:  ~/.cf-terraforming.yaml configured per Cloudflare instructions

```
cf-terraforming generate --resource-type "cloudflare_zone" --account be******a6e44caa49c91b6******432 --verbose
DEBU[0000] initializing cloudflare-go                    account_id=be******a6e44caa49c91b6******432 email=user@example.com zone_id=
DEBU[0000] configuring Cloudflare API with account       account_id=be******a6e44caa49c91b6******432
DEBU[0002] initialising Terraform in .
FATA[0002] configuration is invalid
```

The script and its output are attached below.

[sanitized-script.sh.txt](https://github.com/cloudflare/cf-terraforming/files/7208441/sanitized-script.sh.txt)

[terraform-import.tf.txt](https://github.com/cloudflare/cf-terraforming/files/7208442/terraform-import.tf.txt)

Another interesting notation I made is that, once the cf-terraforming encountered the Fatal error, it seemed to make all of the following runs error out Fatally, too.  I found it quite odd.  I was able to somewhat validate this by shortening the list to resource-types that I knew had values to return and that I was entitled to.  I "generated" them, and, when one threw an error (ironically, cloudflare_zone), I moved it around.  Every iteration after cloudflare_zone failed with Fatal error 0002.  You can see some of that debugging in the script.

My environment:  MacOS BigSur (fully patched as of 21-Sep-2021 early AM) running zsh and homebrew.  I installed Go, Terraform, and cf-terraforming using Homebrew and (for cf-terraforming) the instructions in this repo's README.MD file, plus instructions located at https://developers.cloudflare.com/terraform/advanced-topics/import-cloudflare-resources.

### Steps to reproduce

1. Unsanitize the script with your own information.
2. run the script

**Comment by jacobbednarz** [comment]
Thanks for raising this one @chris-zenfolio. I've left some notes below for inline with your comments.

> What is error code 0002?

The '0002' isn't an error code; it's just a process ticker that the logging library provides. You don't really need this at all, and it's only useful for people digging into the process generating the logs (i.e rarely anyone). This value also disappears if you end up using a different formatter like JSON.

> What specifically is wrong with the "configuration"? Did I miss a parameter? Did the API return a weird value because I queried for a feature not supported/enabled on my account?

Using the existing log lines as markers, I narrowed down the message to come from https://github.com/cloudflare/cf-terraforming/blob/43775a64ed0378ff6149fead541a7ff7fd272312/internal/app/cf-terraforming/cmd/generate.go#L65

This indicates a problem with initialising Terraform itself; the error is being raised from `tfexec` and passed through without any modification. I can see it's definitely sparse though so I'm 👍 to a PR extending the error message to include a prefix to help narrow down the issue.

> since, despite the Cloudflare Blog's statements otherwise, you cannot query for "all"

I suspect you're referring to an older blog entry. There have been major developments since then and the `all` command was dropped in favour of explicitness as not all resources are manageable by customers or had support in cf-terraforming. If you're after a more up to date guide, you can check out the [developer documentation](https://developers.cloudflare.com/terraform/advanced-topics/import-cloudflare-resources) or the more recent [blog entry](https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/). The README in this repository also offers some guidance on how to use the tool if you haven't already seen that.

As there isn't necessarily anything to action here, I'm closing this one off, and you're welcome to open a PR updating the error message otherwise I'll add it in an upcoming PR. If you have further questions, I'm happy to elaborate.
