### ISSUE TITLE
cf-terraforming does not successfully execute when using OpenTofu

### ISSUE THREAD

**Issue by CyberiumShadow** [cloudflare/cf-terraforming#624]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.14.0

### Expected outcome

Successful generation of Terraform configuration of Cloudflare resources using OpenTofu as it is a drop-in replacement for Terraform

### Actual outcome

An error "failed to detect provider installation" occurs when the binary path for OpenTofu is provided.
If the binary is not specified, cf-terraforming attempts to use the temporary Terraform binary and throws an error about the backend configuration block has changed.

### Steps to reproduce

1. Install OpenTofu (https://opentofu.org/docs/intro/install/)
2. Run `cf-terraforming generate --zone xxxxxxxxxxxxx --resource-type "cloudflare_record" --terraform-binary-path "/usr/local/bin/tofu"`
3. Receive error.

**Comment by jacobbednarz** [comment]
have you initialised the terraform configuration correctly? the line you are seeing an error from is about not having the provider accessible - https://github.com/cloudflare/cf-terraforming/blob/86c85c7f1716556f74f2cf36568db77633b16c78/internal/app/cf-terraforming/cmd/generate.go#L88

**Comment by kdpuvvadi** [comment]
I can confim this. Woking fine when using terraform but with tofu throwing error. Tested this is on windows and debian. cf-t assuming we are running with terraform not other alternatives.

```shell
$ cf-terraforming generate --resource-type "cloudflare_record" --zone $ENV:CF_ZONE_ID1
time="2023-10-30T10:06:35+05:30" level=fatal msg="failed to read provider schemaexit status 1 
Error: Inconsistent dependency lock file. 
The following dependency selections recorded in the lock file are inconsistent with the current configuration:
  - provider registry.terraform.io/cloudflare/cloudflare: required by this configuration but no version is selected
  - To update the locked dependency selections to match a changed configuration,
  - run: terraform init -upgrade"
```

when path to tofu provided

```shell
$ cf-terraforming generate --resource-type "cloudflare_record" --zone $ENV:CF_ZONE_ID1--terraform-binary-path $ENV:LOCALAPPDATA\Microsoft\WinGet\Links\tofu.exe'
time="2023-10-30T10:09:19+05:30" level=fatal msg="failed to detect provider installation"
```

**Comment by jacobbednarz** [comment]
thanks, I'll have a dig sometime next week however, if opentofu isn't compatible with the `tfexec` library that we are using, it's unlikely we'll support it.

**Comment by kdpuvvadi** [comment]
opentofu does infact use `tfexec`

**Comment by jacobbednarz** [comment]
@kdpuvvadi can you please link to where you are seeing this? terraform core does not use `tfexec` so i wouldn't expect opentofu to be using it either given it is just a fork at v1.4. 

my previous inquiry is about the compatibility of opentofu _in_ `tfexec` which provides programmatic access to the commands offered by terraform.

**Comment by jacobbednarz** [comment]
i tracked down the issue here and it's twofold.

1. opentofu is not compatible with existing state files when it comes to the provider registry. it looks like as part of their giant find and replace PR, they updated the hostnames used for the registry but don't implement any fallback or retry logic to attempt to use the hashicorp registry. which leads me to part 2...
2. within cf-terraforming, we [query for the provider schema](https://github.com/cloudflare/cf-terraforming/blob/902ca887d272f8ac249fabcd971110bbbb9d69d2/internal/app/cf-terraforming/cmd/generate.go#L86-L89) however, because of my first point, the binary *does not* actually find the provider that lives in registry.terraform.io (so the error message was correct here).

i've opened #630 to address this however, the onus is on the user to pass in both the correct flags (`--provider-registry-hostname` and `--terraform-binary-path`) as we will continue defaulting to the hashicorp registry.

**Comment by Firefishy** [comment]
Here is a working example to help others:

```
cf-terraforming --account xxxxx --email xxxxx --token xxxxx --modern-import-block --provider-registry-hostname registry.opentofu.org --terraform-binary-path /opt/homebrew/bin/tofu generate --resource-type cloudflare_zone
```
