### ISSUE TITLE
Bulk import zone-level resources using the account specifier

### ISSUE THREAD

**Issue by Schachte** [cloudflare/cf-terraforming#646]
### Current `cf-terraforming` version

cf-terraforming 0.16.1

### Description

For users that have a large number of zones, importing configuration by zone doesn't really make sense IMO. It would be nice to be able to say `--account` instead of `--zone` for things like page rules when doing bulk imports. 

### Use cases

The way I see it, if I have 150+ zones and I'm onboarding to Terraform, then I need to manually import zone-level resources by zone. This can be very time consuming if an account has a lot of zones. 

It would be nice to just say "Out of the N number of zones I have, import all the things for resource X". From the docs, it wasn't clear if this exists or not, but attempting it fails when trying to import something like page rules using the account arg. 

### Potential `cf-terraforming` usage

Curious on thoughts before getting too deep in the weeds here. However, I really just envision matching the account arg and zone-level resource and slightly adjusting the iteration logic. 

Importing page rules with `--account` would first aggregate all the zones. From there, we would do whatever we do for a single zone but imports would happen as an aggregate instead of a single zone. 

https://github.com/cloudflare/cf-terraforming/blob/master/internal/app/cf-terraforming/cmd/generate.go#L615

Take this line for example. It makes an assumption that zone-id is preferred, but in my case it wouldn't be. If we do some pre-processing step to wrap this logic in loop of all zones then things would be much simpler. 

### References

n/a

**Comment by Schachte** [comment]
```
		case "cloudflare_page_rule":
			var zoneStructData []interface{}
			zonePayload, err := api.ListZones(context.Background())
			if err != nil {
				log.Fatal(err)
			}

			zoneResourceCount := len(zonePayload)
			zoneM, _ := json.Marshal(zonePayload)
			err = json.Unmarshal(zoneM, &zoneStructData)
			if err != nil {
				log.Fatal(err)
			}

			for i := 0; i < zoneResourceCount; i++ {
				zoneID := zoneStructData[i].(map[string]interface{})["id"].(string)
				jsonPayload, err := api.ListPageRules(context.Background(), zoneID)
```

I have a POC of this running locally.

**Comment by jacobbednarz** [comment]
this is an intentional design decision due to the way the permissioning side of things works. this tool used to have an `--all` option that we deprecated due to the amount of edge cases it hit and we didn't have a great way of resolving when they were encountered.

adding the ability to dump all resources in accounts or zones isn't something we'd like to see back into the library. however, something we've been toying with is the ability to pass in multiple resources explicitly.

> but attempting it fails when trying to import something like page rules using the account arg.

this doesn't work because page rules don't exist at the account level (they are zone resources) and we don't have a reliable way to transverse all accounts to get the inner resources. instead, you need to tell the tool specifically which zone to act upon. again, this was another design decision to the edge cases in the resource relationships and the inability to differentiate against no resources and invalid permissions on tokens.

**Comment by Schachte** [comment]
@jacobbednarz That seems reasonable. Maybe a compromise would be specifying zone ids as an array then in addition to specifying resources to generate + import as an array?

````
cf-terraforming 
  --zone=[1,2,3,4]
  --resource=[page_rule, cloudflare_record...]
```

**Comment by jacobbednarz** [comment]
the usage would be still be limited to one zone (or account since that is where the permission boundary exists)  and the resources would be iterable. 

```
--resource "cloudflare_record,cloudflare_page_rule,..."
```

similarly for the account level resources. 

as I mentioned before, we previously had an option to do what you're asking and it was difficult to debug, difficult to maintain and hard to get right as a consumer so unfortunately, we won't be adding it back until those issues (permissioning being one of the largest) has a better solution. sorry!

you're obviously welcome to patch this anyway you want for your usage but it won't be something we can accept in the main project today. interested to see what you come up with though so hit me up internally when it is ready!
